function surface_particles = findSurfaceParticles()
    % R-1 = -m * A m,dwdr,rho_j,rPos
    rNorm = sqrt(rPos(:,1).*rPos(:,1)+rPos(:,2).*rPos(:,2)); 
    a11_ij = dwdr.*rPos(:,1).*rPos(:,1)./(rho_j.*rNorm)); 
    a12_ij = dwdr.*rPos(:,1).*rPos(:,2)./(rho_j.*rNorm)); 
    a12_ij = dwdr.*rPos(:,2).*rPos(:,2)./(rho_j.*rNorm)); 
    trA = sum(a11_ij) + sum(a22_ij);
    detA = sum(a11_ij)*sum(a22_ij) - sum(a12_ij)*sum(a12_ij);
    lambda1 = -m * 0.5 * (trA + sqrt(trA*trA - 4 detA));
    lambda2 = -m * 0.5 * (trA - sqrt(trA*trA - 4 detA));
